# Generated by Django 4.2.11 on 2024-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_deleted',
        ),
    ]
